### ISSUE TITLE
installing ReFrame in software layer fails, mixup with ReFrame installation in compat layer

### ISSUE THREAD

**Issue by boegel** [EESSI/software-layer#127]
We added ReFrame to the 2021.06 compat layer (cfr. https://github.com/EESSI/gentoo-overlay/pull/41), and now the installation of ReFrame in the 2021.06 software layer is failing:

```
== 2021-08-26 14:33:05,527 build_log.py:169 ERROR EasyBuild crashed with an error (at easybuild/base/exceptions.py:124 in __init__): Sanity check failed: sanity check command reframe -V exited with code 1 (output: Traceback (most recent call last):
  File "/cvmfs/pilot.eessi-hpc.org/2021.06/software/linux/aarch64/graviton2/software/ReFrame/3.6.2/bin/reframe", line 4, in <module>
    __import__('pkg_resources').run_script('ReFrame-HPC==3.6.2', 'reframe')
  File "/cvmfs/pilot.eessi-hpc.org/2021.06/software/linux/aarch64/graviton2/software/ReFrame/3.6.2/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/cvmfs/pilot.eessi-hpc.org/2021.06/software/linux/aarch64/graviton2/software/ReFrame/3.6.2/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1436, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/reframe' not found in metadata at '/cvmfs/pilot.eessi-hpc.org/2021.06/compat/linux/aarch64/usr/lib/python3.9/site-packages/ReFrame_HPC-3.6.2-py3.9.egg-info'
```

It should be looking into `/cvmfs/pilot.eessi-hpc.org/2021.06/software/linux/aarch64/software/ReFrame/3.6.2`, not in `/cvmfs/pilot.eessi-hpc.org/2021.06/compat/...`.

This probably happens because `pkg_resources` always looks in the Python installation itself before taking into account `$PYTHONPATH`.

**Comment by boegel** [comment]
Rather than also installing ReFrame in the software layer, we should only have it in the compat layer?

**Comment by ocaisa** [comment]
I think this is pretty stale, we use ReFrame in every build so the problem is solved
