### ISSUE TITLE
installing Rust fails because glibc of host OS is picked up by cargo binary used to bootstrap Rust

### ISSUE THREAD

**Issue by boegel** [EESSI/software-layer#157]
While trying to install `foss/2021a`, I ran into a snag when building `Rust` (which is a build dependency for `Python`, which is required as a build dependency for `FlexiBLAS`).

Here's the problem popping up:

```
error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libproc_macro_error_attr-fbfef320d848b049.so)
   --> /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:284:9
    |
284 | pub use proc_macro_error_attr::proc_macro_error;
    |         ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `proc-macro-error`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
Traceback (most recent call last):
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 1192, in <module>
    main()
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 1175, in main
    bootstrap(help_triggered)
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 1148, in bootstrap
    build.build_bootstrap()
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 900, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 153, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/Cargo.toml
make: *** [Makefile:12: all] Error 1
```

The problem seems to be that a pre-built set of binaries is being downloaded and used to bootstrap Rust, but those binaries are picking up host libraries like `/lib/x86_64-linux-gnu/libc.so.6` rather than using `libc.so.6` from the compat layer.

**Comment by boegel** [comment]
A naive attempt to set `$LD_LIBRARY_PATH` to `$EPREFIX/lib64` so the right `libc.so.6` would be picked up didn't get me very far.

I added this to the `Rust` easyconfig:

```python
prebuildopts += "export LD_LIBRARY_PATH=$EPREFIX/lib64 && "
```
(where `$EPREFIX` contains a path like `/cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64`)

Which results in:
```
running: /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/Cargo.toml
/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo: relocation error: /cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64/lib64/libc.so.6: symbol _dl_catch_error_ptr version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
Traceback (most recent call last):
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 1192, in <module>
    main()
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 1175, in main
    bootstrap(help_triggered)
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 1148, in bootstrap
    build.build_bootstrap()
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 900, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 153, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/Cargo.toml
make: *** [Makefile:12: all] Error 1
```

**Comment by boegel** [comment]
More details be enabling `verbose = 2` in `config.toml`:

```
   Compiling ignore v0.4.16
     Running `/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/rustc --crate-name ignore /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/cargo/registry/src/github.com-1ecc6299db9ec823/ignore-0.4.16/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=cda83e19acb97bca -C extra-filename=-cda83e19acb97bca --out-dir /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps -L dependency=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps --extern crossbeam_utils=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libcrossbeam_utils-029064ca55ee7f18.rmeta --extern globset=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libglobset-692b5c6aea40578c.rmeta --extern lazy_static=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/liblazy_static-1fa5e8b52f04e552.rmeta --extern log=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/liblog-62488b780878ac10.rmeta --extern memchr=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libmemchr-4ac283659cfabdc0.rmeta --extern regex=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libregex-22c24edd710f1310.rmeta --extern same_file=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libsame_file-4590c7908f3d75d8.rmeta --extern thread_local=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libthread_local-b9a0c21f625b2344.rmeta --extern walkdir=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libwalkdir-f19d31d3e7f51b67.rmeta --cap-lints allow -Cdebuginfo=2 -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings`
     Running `/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/rustc --crate-name proc_macro_error --edition=2018 /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="syn"' --cfg 'feature="syn-error"' -C metadata=c51edccf67fc5031 -C extra-filename=-c51edccf67fc5031 --out-dir /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps -L dependency=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps --extern proc_macro_error_attr=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libproc_macro_error_attr-fbfef320d848b049.so --extern proc_macro2=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libproc_macro2-a75232f6de2f6337.rmeta --extern quote=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libquote-130d1365fbf1da07.rmeta --extern syn=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libsyn-ba667ab8b0e9bb9f.rmeta --cap-lints allow -Cdebuginfo=2 -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings --cfg use_fallback`
error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libproc_macro_error_attr-fbfef320d848b049.so)
   --> /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:284:9
    |
284 | pub use proc_macro_error_attr::proc_macro_error;
    |         ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `proc-macro-error`

Caused by:
  process didn't exit successfully: `/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/rustc --crate-name proc_macro_error --edition=2018 /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="syn"' --cfg 'feature="syn-error"' -C metadata=c51edccf67fc5031 -C extra-filename=-c51edccf67fc5031 --out-dir /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps -L dependency=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps --extern proc_macro_error_attr=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libproc_macro_error_attr-fbfef320d848b049.so --extern proc_macro2=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libproc_macro2-a75232f6de2f6337.rmeta --extern quote=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libquote-130d1365fbf1da07.rmeta --extern syn=/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/bootstrap/debug/deps/libsyn-ba667ab8b0e9bb9f.rmeta --cap-lints allow -Cdebuginfo=2 -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings --cfg use_fallback` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
Traceback (most recent call last):
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 1192, in <module>
    main()
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 1175, in main
    bootstrap(help_triggered)
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 1148, in bootstrap
    build.build_bootstrap()
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 900, in build_bootstrap
    run(args, env=env, verbose=self.verbose)
  File "/tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/bootstrap.py", line 153, in run
    raise RuntimeError(err)
RuntimeError: failed to run: /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/src/bootstrap/Cargo.toml --verbose
make: *** [Makefile:12: all] Error 1
```

**Comment by boegel** [comment]
The problem seems to be the hardcoded path to ELF interpreter used by the pre-built `rustc` binary:

```
[EESSI pilot 2021.12] $ ldd /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/rustc | grep ld-linux
 /lib64/ld-linux-x86-64.so.2 => /cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64/lib64/ld-linux-x86-64.so.2 (0x00007f3e6dfdb000)
```

The `/lib64/ld-linux-x86-64.so.2` can be changed with `patchelf`:

```
patchelf --set-interpreter $EPREFIX/lib64/ld-linux-x86-64.so.2 /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/rustc
```

result:

```
$ ldd /tmp/boegel/easybuild/build/Rust/1.52.1/GCCcore-10.3.0/rustc-1.52.1-src/build/x86_64-unknown-linux-gnu/stage0/bin/rustc | grep ld-linux
 /cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/x86_64/lib64/ld-linux-x86-64.so.2 (0x00007f842fd02000)
```

With this patched `rustc` binary, I can manually run the failing `rustc` command, so the question now is how to squeeze that `patchelf` command into the Rust bootstrap procedure...

**Comment by mboisson** [comment]
https://github.com/ComputeCanada/easybuild-easyconfigs-installed-avx2/blob/main/2020/Rust/Rust-1.53.0.eb

That's what we use as a recipe. We don't bootstrap, we install the binary version.

**Comment by mboisson** [comment]
> A naive attempt to set `$LD_LIBRARY_PATH` to `$EPREFIX/lib64` so the right `libc.so.6` would be picked up didn't get me very far.

This can *never* bring anything other than tears. Don't set `LD_LIBRARY_PATH` to `EPREFIX/lib64`

**Comment by boegel** [comment]
I came up with a (still dirty) patch that seems to fix the issue (build hasn't completed yet though):

```diff
--- rustc-1.52.1-src/src/bootstrap/bootstrap.py.orig    2021-05-09 02:52:39.000000000 +0000
+++ rustc-1.52.1-src/src/bootstrap/bootstrap.py 2021-12-15 21:09:52.086251947 +0000
@@ -565,6 +565,12 @@
         if ostype != "Linux":
             return

+        eprefix = os.getenv("EPREFIX")
+        if eprefix and not fname.endswith(".so"):
+            interpreter_path = os.path.join(eprefix, "lib64", "ld-linux-x86-64.so.2")
+            cmd = ["patchelf", "--set-interpreter", interpreter_path, fname]
+            run(cmd, verbose=True)
+
         if not os.path.exists("/etc/NIXOS"):
             return
         if os.path.exists("/lib"):
```

Of course this will need to be refined a bit.

The good news is that the `bootstrap.py` script actually already does something very similar for `NixOS`, so perhaps a nicely worked out patch can even be pushed upstream...

**Comment by ocaisa** [comment]
Somebody has looked into this...https://github.com/dtolnay/bootstrap

**Comment by boegel** [comment]
Proper patch implemented, see https://github.com/easybuilders/easybuild-easyconfigs/pull/14584

**Comment by ocaisa** [comment]
This is resolved by https://github.com/easybuilders/easybuild-easyconfigs/pull/15586...though I'm a bit surprised that `patchelf` is not included as a builddep in that PR since that is actually required for the patch to work.

**Comment by boegel** [comment]
Adding `patchelf` as a build dependency doesn't help, since build dependencies are only loaded *after* patches are applied.
See also https://github.com/easybuilders/easybuild-framework/issues/1376

**Comment by ocaisa** [comment]
@boegel But that patch doesn't _run_ `patchelf`, it only makes it a requirement during the build process.
