### ISSUE TITLE
2021.12 pilot fails to find best target on RPi4

### ISSUE THREAD

**Issue by bedroge** [EESSI/software-layer#171]
On a `Raspberry Pi 4 Model B Rev 1.1`, I get the following error when sourcing the init script:

```
Singularity> source /cvmfs/pilot.eessi-hpc.org/versions/2021.12/init/bash 
Found EESSI pilot repo @ /cvmfs/pilot.eessi-hpc.org/versions/2021.12!
Traceback (most recent call last):
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/init/eessi_software_subdir_for_host.py", line 141, in <module>
    main()
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/init/eessi_software_subdir_for_host.py", line 135, in main
    target = find_best_target(eessi_prefix)
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/init/eessi_software_subdir_for_host.py", line 76, in find_best_target
    host_cpu_family, host_vendor, host_cpu_name = det_host_triple()
  File "/cvmfs/pilot.eessi-hpc.org/versions/2021.12/init/eessi_software_subdir_for_host.py", line 55, in det_host_triple
    host_cpu = max(non_generic_compat_targets, key=sorting_fn)
ValueError: max() arg is an empty sequence
ERROR: no value set for $EESSI_SOFTWARE_SUBDIR
```

```
Singularity> /cvmfs/pilot.eessi-hpc.org/versions/2021.12/compat/linux/aarch64/usr/bin/archspec cpu
aarch64
```

This does work with pilot 2021.06, so I guess it's related to the changes related to the new archspec version?

**Comment by boegel** [comment]
See also #142 and #112

**Comment by hmeiland** [comment]
can you please add/insert /proc/cpuinfo to add/verify target to archdetect?

**Comment by bedroge** [comment]
Our RPi4 cluster is currently down, but this is from another RPi4 (thanks @erijpkema!):

```
$ cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2835
Revision        : c03111
Serial          : 100000006a46d813
Model           : Raspberry Pi 4 Model B Rev 1.1
```

**Comment by bedroge** [comment]
This should work fine now in the production repo, also see https://github.com/EESSI/software-layer/pull/540.
