### ISSUE TITLE
Python installation fails if zlib is in filter-deps

### ISSUE THREAD

**Issue by bedroge** [EESSI/software-layer#20]
During the installation step of `Python/3.8.2-GCCcore-9.3.0`, I get:

```
Traceback (most recent call last):
  File "<frozen zipimport>", line 520, in _get_decompress_func
ModuleNotFoundError: No module named 'zlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen zipimport>", line 568, in _get_data
  File "<frozen zipimport>", line 523, in _get_decompress_func
zipimport.ZipImportError: can't decompress data; zlib not available
```

**Comment by bedroge** [comment]
I also found the following in the log (seems like it can't find any of the libraries that we are added to `filter-deps`?)

```
Python build finished successfully!
The necessary bits to build these optional modules were not found:
_bz2                  _curses               _curses_panel      
_dbm                  _gdbm                 _hashlib           
_lzma                 _ssl                  _tkinter           
readline              zlib                                     
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                  atexit                pwd                
time                                                           


Could not build the ssl module!
Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().
LibreSSL 2.6.4 and earlier do not provide the necessary APIs, https://github.com/libressl-portable/portable/issues/381
```

**Comment by bedroge** [comment]
I didn't include `sysroot` in my Easybuild config, retrying now...

**Comment by boegel** [comment]
It's working fine for me as long as I configure EasyBuild with `--sysroot=$EPREFIX`

**Comment by bedroge** [comment]
Python installed without issues when `sysroot` was set, closing this issue...
