### ISSUE TITLE
failing sanity check for openssl for older `Python` installations on top of EESSI 2023.04 compat layer (due to OpenSSL 3.0.x)

### ISSUE THREAD

**Issue by boegel** [EESSI/software-layer#258]
The installation of both `Python/3.9.5-GCCcore-10.3.0` and `Python/3.9.6-GCCcore-11.2.0` on top of the EESSI 2023.04 compat layer fails (with `OpenSSL` in `filter-deps` in the EasyBuild configuration, cfr. #256) in the sanity check with:

```
== 2023-06-06 20:22:18,752 build_log.py:171 ERROR EasyBuild crashed with an error (at easybuild/tools/build_log.py:111 in caller_info): cmd "python -c 'from cryptography.hazmat.bindings.openssl import binding'" exited with exit code 1 and output:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/cvmfs/pilot.eessi-hpc.org/versions/2023.04/software/linux/x86_64/amd/zen3/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: /cvmfs/pilot.eessi-hpc.org/versions/2023.04/software/linux/x86_64/amd/zen3/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so: undefined symbol: FIPS_mode_set
```

The culprit here most likely is that the version of the `cryptography` extension included in these `Python` easyconfigs is too old, since `cryptography` only seems to support OpenSSL 3.0.x starting with v35.0, cfr. https://cryptography.io/en/latest/changelog/#v35-0-0 . 

(note that the version of the `Rust` build dependency for these `Python` installations had to be bumped to get to this point, cfr. #257)

**Comment by boegel** [comment]
Problem fixed in new EESSI pilot version 2023.06 by sticking to OpenSSL 1.1.1 for now in compat layer, cfr. https://github.com/EESSI/compatibility-layer/pull/188
